Curatio/ViewModels/Form3ListViewModel.cs
using Curatio.Models.Form3;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Curatio.ViewModels
{
    public class Form3ListViewModel
    {
        public IEnumerable<Form3> Form3s { get; set; }
    }
}

Curatio/Controllers/Form3Controller.cs
using AutoMapper;
using ClosedXML.Excel;
using Curatio.Data;
using Curatio.Models.Form3;
using Curatio.Repository;
using Curatio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Curatio.Controllers
{
    public class Form3Controller : Controller
    {
        #region DependencyInjection

        private readonly AppDbContext _context;
        private readonly IFormThree _formThreeRepo;
        private readonly IMapper _mapper;

        public Form3Controller(
            AppDbContext context,
            IFormThree formThreeRepo,
            IMapper mapper
            )
        {
            _context = context;
            _formThreeRepo = formThreeRepo;
            _mapper = mapper;
        }
        #endregion

        #region GetFormThrees
        [HttpGet]
        public ViewResult Form3List(FilterForm3 body)
        {
            var allForm3s = _formThreeRepo.GetAllForm3s();

            if (body == null)
            {
                return View(new Form3ListViewModel { Form3s = allForm3s });

            }
            else
            {
                var filtered = _formThreeRepo.FilteredForm3s(body);
                return View(new Form3ListViewModel { Form3s = filtered });
            }
        }
        #endregion

        #region FormThreeDetails

        public IActionResult Form3Details(int id)
        {
            var details = _context.FormThree.FirstOrDefault(d => d.Id == id);
            if (details == null)
            {
                return NotFound();
            }

            return View(details);
        }
        #endregion

        #region AddFormThree
        public IActionResult Form3Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Form3ForCreation body)
        {
            var formThreeEntity = _mapper.Map<Form3>(body);
            _formThreeRepo.CreateFormThree(formThreeEntity);
            await _context.SaveChangesAsync();

            return RedirectToAction("Form3List");
        }
        #endregion

        #region UpdateFormThree
        public IActionResult Form3Edit(int id)
        {
            var info = _context.FormThree.FirstOrDefault(d => d.Id == id);
            if (info == null)
            {
                return NotFound();
            }

            return View(info);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Form3ForUpdate body)
        {
            var formThreeEntity = _mapper.Map<Form3>(body);
            formThreeEntity.Id = id;

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var getFormById = _context.FormThree.Any(d => d.Id == formThreeEntity.Id);
            if (!getFormById)
            {
                return BadRequest();
            }

            _formThreeRepo.UpdateFormThree(formThreeEntity);
            await _context.SaveChangesAsync();

            return RedirectToAction("Form3List");
        }
        #endregion

        #region DeleteFormThree
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var body = await _context.FormThree.FindAsync(id);
            if (body == null)
            {
                return NotFound();
            }

            _context.FormThree.Remove(body);
            await _context.SaveChangesAsync();

            return RedirectToAction("Form3List");
        }
        #endregion

        #region ExportToExcel

        public IActionResult ExportToExcel()
        {
            var allforms = _context.FormThree;
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Users");
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Id";
                worksheet.Cell(currentRow, 2).Value = "Company";
                worksheet.Cell(currentRow, 3).Value = "DoctorName";
                worksheet.Cell(currentRow, 4).Value = "DoctorEmail";
                worksheet.Cell(currentRow, 5).Value = "DoctorPhone";
                worksheet.Cell(currentRow, 6).Value = "Date";
                worksheet.Cell(currentRow, 7).Value = "FullName";
                worksheet.Cell(currentRow, 8).Value = "Address";
                worksheet.Cell(currentRow, 9).Value = "Province";
                worksheet.Cell(currentRow, 10).Value = "Email";
                worksheet.Cell(currentRow, 11).Value = "Phone";
                worksheet.Cell(currentRow, 12).Value = "PrivateId";
                worksheet.Cell(currentRow, 13).Value = "Researches";
                worksheet.Cell(currentRow, 14).Value = "Transport";
                worksheet.Cell(currentRow, 15).Value = "Comment";

                foreach (var form in allforms)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = form.Id;
                    worksheet.Cell(currentRow, 2).Value = form.Company;
                    worksheet.Cell(currentRow, 3).Value = form.DoctorName;
                    worksheet.Cell(currentRow, 4).Value = form.DoctorEmail;
                    worksheet.Cell(currentRow, 5).Value = form.DoctorPhone;
                    worksheet.Cell(currentRow, 6).Value = form.Date;
                    worksheet.Cell(currentRow, 7).Value = form.FullName;
                    worksheet.Cell(currentRow, 8).Value = form.Address;
                    worksheet.Cell(currentRow, 9).Value = form.Province;
                    worksheet.Cell(currentRow, 10).Value = form.Email;
                    worksheet.Cell(currentRow, 11).Value = form.Phone;
                    worksheet.Cell(currentRow, 12).Value = form.PrivateId;
                    worksheet.Cell(currentRow, 13).Value = form.Researches;
                    worksheet.Cell(currentRow, 14).Value = form.Transport;
                    worksheet.Cell(currentRow, 15).Value = form.Comment;

                    worksheet.Cell(currentRow, 13).Style.Font.FontSize = 9;
                    worksheet.Cell(currentRow, 15).Style.Font.FontSize = 9;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "users.xlsx");
                }

            }
        }
        #endregion
    }
}

Curatio/Views/Shared/Form3Partial/_Form3List.cshtml
@model Form3

    <tbody>
        <tr class="font-size table-secondary">
            <td>@Model.Id</td>
            <td>@Model.FullName</td>
            <td>@Model.Company</td>
            <td>@Model.Province</td>
            <td>@Model.DoctorName</td>
            <td>@Model.Phone</td>
            <td>@Model.PrivateId</td>
            <td><a asp-controller="Form3" asp-action="Form3Details" asp-route-id="@Model.Id" class="btn btn-sm btn-primary bi-info-circle-fill"></a></td>
            <td><a asp-controller="Form3" asp-action="Form3Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-warning bi bi-pencil-square"></a></td>
            <td>
                <form asp-controller="Form3" asp-action="Delete" asp-route-id="@Model.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger bi bi-trash" onclick="return confirm('Are you sure you want to delete Form3: @Model.Id')"></button>
                </form>
            </td>
        </tr>
    </tbody>

Curatio/Views/Shared/Form3Partial/_Form3ListCard.cshtml
@model Form3

<style>
    .center-card {
        margin: auto;
    }
</style>

<div class="card mt-3 showCard center-card" style="width: 22rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.FullName</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.PrivateId</h6>
        <div class="card-text">
            <p class="card-text">
                <strong>Transport: </strong> 
                @if (Model.Transport)
                {
                    <span>Yes</span>
                }
                else
                {
                    <span>No</span>
                }
            </p>
            <p><strong>Doctors Name: </strong>@Model.DoctorName</p>
            <p><strong>Doctors Email: </strong>@Model.DoctorEmail</p>
            <p><strong>Doctors Phone: </strong>@Model.DoctorPhone</p>
        </div>
        <div class="row">
            <div class="d-flex flex-column col-3 m-1">
                <label class="text-dark">Details: </label>
                <a asp-controller="Form3" asp-action="Form3Details" asp-route-id="@Model.Id" class="btn btn-primary"></a>
            </div>
            <div class="d-flex flex-column col-3 m-1">
                <label class="text-dark">Edit: </label>
                <a asp-controller="Form3" asp-action="Form3Edit" asp-route-id="@Model.Id" class="btn btn-warning"></a>
            </div>
            <div class="d-flex flex-column col-3 m-1">
                <label class="text-dark">Delete: </label>
                <button asp-controller="Form3" asp-action="Delete" asp-route-id="@Model.Id" type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete Form3: @Model.Id')"></button>
            </div>
        </div>
    </div>
</div>